//issue

export const REQUEST_ISSUES = 'REQUEST_ISSUES';
export const RECEIVE_ISSUES_SUCCESS = 'RECEIVE_ISSUES_SUCCESS';
export const RECEIVE_ISSUES_ERROR = 'RECEIVE_ISSUES_ERROR';
export const SAVE_ISSUES = 'SAVE_ISSUES';
export const SAVE_ISSUES_SUCCESS = 'SAVE_ISSUES_SUCCESS';
export const SAVE_ISSUES_ERROR = 'SAVE_ISSUES_ERROR';

// user

export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const SET_LOGIN_USER = 'SET_LOGIN_USER';

//vote
